import itertools
from pickle import NONE


class Leaf(object):
    """Leaf
    
    This Class is a node of three generated by 
    the regex in order to work with the direct 
    method

    Args:
        object (id): This must be a string, this
        is a nullable object that can be used to
        define the type of the Leaf. The following
        options are available:
        
        "star" = star or kleene node
        "concat" = concatenation node
        "or" = or node
        None = Leaf node, must be a numeric value
    """
    new_id = itertools.count()
    def __init__(self, value, right=None, left=None, id=None):
        super(Leaf, self).__init__()
        self.id = id if id else next(Leaf.new_id)
        self.value = value
        self.firstpos = []
        self.lastpos = []
        self.nullable = True
        self.followpos = []
        self.right = right                          
        self.left = left
        self.getNullable()
        self.getFirstPos()
        self.getLastPos()
        self.getFollowPos()
        
    def getNullable(self):
        if(self.value=='*'):
            self.nullable = True
        elif(self.value=='|'):
            self.nullable = self.right.nullable or self.left.nullable
        elif(self.value=='•'):
            self.nullable = self.right.nullable and self.left.nullable if (self.right and self.left) else True
        else:
            self.nullable = False
    
    def getFirstPos(self):
        if(self.value=='*'):
            self.firstpos = self.right.firstpos 
        elif(self.right==None or self.left==None):
            self.firstpos = [self]
        elif(self.value=='|'):
            self.firstpos = self.right.firstpos + self.left.firstpos
        elif(self.value=='•'):
            self.firstpos =  self.right.firstpos + self.left.firstpos if self.left.nullable == True else self.left.firstpos
        elif(isinstance(self.id, int)):
            self.firstpos = [self]
        for n in self.firstpos:
            if(not isinstance(n.id, int)):
                self.firstpos.remove(n)
    
    def getLastPos(self):
        if(self.right==None and self.left==None):
            self.lastpos = [self]
        elif(self.value=='*'):
            self.lastpos = self.right.lastpos
        elif(self.value=='|'):
            self.lastpos = self.right.lastpos + self.left.lastpos
        elif(self.value=='•'):
            self.lastpos =  self.right.lastpos + self.left.lastpos if self.right.nullable == True else self.right.lastpos
        elif(isinstance(self.id, int)):
            self.lastpos = [self]
        for n in self.lastpos:
            if(not isinstance(n.id, int)):
                self.firstpos.remove(n)
    
    def getFollowPos(self):
        if(self.value=='*'):
            for i in self.lastpos:
                i.followpos = i.followpos + self.firstpos
        elif(self.value=='•' and self.left):
            for i in self.left.lastpos:
                i.followpos = i.followpos + self.right.firstpos
            
        